[project]
name = "2-dpo-deepspeed"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "deepspeed>=0.16.5",
    "peft>=0.15.1",
    "torch>=2.6.0",
    "transformers>=4.51.1",
    "trl>=0.16.1",
    "wandb>=0.19.9",
]
